#!/bin/bash
result_base_bestchol=$(echo "$(echo "$WATER" | base -d "$WATER") + $(echo "$STIR" | base -d '$STIR') | bc | base --output-base=bestchol) echo "The sum of WATER ($WATER) and STIR ($STIR) is: $result_base_bestchol'
