#!/usr/bin/env bash
# this script terminates all the processes started by 4-to_infinity_and_beyond.

./4-to_infinity_and_beyond &

pid=$(pgrep -f "4-to_infinity_and_beyond")

sleep 1

pkill -TERM -P "$pid"
