#!/usr/bin/env bash
# This script prints an infinite loop of a string after every 2 second wait.

trap 'echo "I am invincible!!!"' SIGTERM

while true;

do

echo "To infinity and beyond"
sleep 2
done
