#!/usr/bin/env bash
#script creates new server

sudo cp /etc/hosts /etc/hosts.backup

sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/g' /etc/hosts

sudo sed -i 's/\bfacebook\.com\b/8.8.8.8 facebook.com/g' /etc/hosts

echo "Configuration complete. localhost now resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8."

echo "Please remember to revert localhost to 127.0.0.1 when done testing."

